import fractal
import turtle
turtle.resetscreen()
turtle.penup()
turtle.forward(-300)
turtle.pendown()
fractal.fractalPeano(0,100)
turtle.penup()
turtle.forward(25)
turtle.pendown()
fractal.fractalPeano(1,100)
turtle.penup()
turtle.forward(25)
turtle.pendown()
fractal.fractalPeano(2,100)
turtle.penup()
turtle.forward(25)
turtle.pendown()
fractal.fractalPeano(3,100)
turtle.penup()
turtle.forward(25)
turtle.pendown()
fractal.fractalPeano(4,100)
